### PR TITLE
Add support for uuid, add clickable toggle

### LINKED ISSUE #21: Use page id on Kirby links instead absolute url
It doesn't make sense for internal page links to have absolute url. Links working in local will be broken when you deploy prod.

### PR DESCRIPTION
**Pull request by tasinttttttt**
- Adds support for kirby3 UUIDS. No more relying on page url = freedom to change slugs. Breaking change though.
- Add "clickable" toggle.

Resolves #21 and possibly #16

### CODE REVIEW

**Comment by tasinttttttt** [comment]
resolves #21

**Comment by eXpl0it3r** [comment]
Works great, thank you! 🙂 

Might want to update the example in the readme to use the uuid instead of the url.

**Comment by tinogithub** [comment]
First, thank you for the idea.
However I am struggling on how to change my navigation bar links. How do I change this line i.e.?
`<a href="<?php echo $child->url() ?>">`
I expected to do
`<a href="<?php echo $child->uuid()->url() ?>">`

Every menu link now shows the corresponding UUID-link like "page://ArzOvYFUxVlEBFyu"  but the page won't load after clicking.

Thank you for help

**Comment by afbora** [comment]
What about `uuid` feature disabled from the config?

**Comment by sachbearbeiter** [comment]
Thanks for the pull request. Please see the current version 4 for new improvements.

**Pull request closed without merging**
